VERSION 0.7
FROM python:3

deps:
    WORKDIR /health_fitness_app/
    RUN pip install --upgrade pip
    RUN pip install wheel
    COPY ../../requirements.txt ./
    RUN pip wheel -r requirements.txt --wheel-dir=wheels
    SAVE ARTIFACT wheels /wheels

build:
    FROM +deps
    COPY health_fitness_app/bmi_service health_fitness_app/bmi_service
    SAVE ARTIFACT health_fitness_app/bmi_service health_fitness_app/bmi_service

unit-test:
    FROM +build
    COPY health_fitness_app/bmi_service/test_bmi_service.py .
    RUN pytest health_fitness_app/bmi_service/test_bmi_service.py

# docker:
#     COPY +deps/wheels wheels
#     COPY +build/health_fitness_app/bmi_service health_fitness_app/bmi_service
#     COPY ../../requirements.txt ./
#     ARG tag='latest'
#     RUN pip install --no-index --find-links=wheels -r requirements.txt
#     ENTRYPOINT ["python3", "./src/hello.py"]
#     # SAVE IMAGE python-example:$tag